# Generated by Django 3.2.7 on 2022-06-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_enquiry_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
